---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
  download artifact:
    runs-on: unbuntu-lastest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run e2e:headless
'on': [push]