---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - uses: actions/cache@v3
        with:
          path: node_mobules
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_mobules
      - run: npm run e2e:headless
      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: cypress/videos
'on': [push]