---
# jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '14'
#       - run: ls -lah
#       - run: npm install -g bats
#       - run: bats -v
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #       with:  
  #         path: |
  #           node_modules
  #           /home/runner/.cache/Cypress
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #     - run: npm install
  #     - run: npm run build
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #       with:  
  #         path: |
  #             node_modules
  #             /home/runner/.cache/Cypress
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #     - run: npm run e2e:headless
  #     - if: always()
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: my-artifact
  #         path: cypress/videos

    # deploy:
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: webfactory/ssh-agent@v0.8.0
    #     with:
    #       ssh-private-key: ${{ secrets.SSH_KEY }}
    #   - run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd CICD && git pull && npm install && npm run build && pm2 restart all"

'on': [push]
